-- apply_trims.lua — PLAN 1b.3 (2026-09-19): the ABSOLUTE trims onto the rack.
-- GENERATED by tools/gen_apply_trims.js from bank/trims.json — do not edit the table by hand.
-- Idempotent, self-reporting, and it NEVER saves: his CTRL+S.
--
-- The target (RUNNING_LOG §83): a 9-voice tutti at -20 LUFS-S, so each voice at
-- -29.54 LUFS = -31.84 dB on the instrument card's scale. Every instrument in this table
-- comes DOWN: the rack was 7–21 dB hot because 0d balanced it relatively, through a REC bus trimmed
-- 12 dB down, with nothing saying how loud the ensemble should BE (§76).
--
-- Each row: the Reaper FADER carries up to +12 dB (its ceiling); any remainder goes into a stock
-- "JS: Volume Adjustment" (utility/volume) FX on the track — Reaper-side, no MIDI binding, so no CC7 can
-- ever overwrite it (ARO's own gain is bound to CC7 and tops out at unity — §58; #5's SI2 parts had the same
-- trap). A track with no remainder gets no FX; an existing one is set to 0 rather than removed.
-- The SI2 `b` instances carry their instrument's trim too — the same instrument, its curve copies — and so
-- do **Horn SI2 high** and **Horn SI2 b high**, the ReaPitch path of 1a.1, which 0d's hand-typed table
-- predated and which have therefore never been trimmed at all.
--   node tools/reaper_job.js run reaper/bridge/jobs/apply_trims.lua
local JS_NAME = 'utility/volume'
local TRIMS = {
  { name = "Bass Flute XS", faderDb = 5.52, extraDb = 0.00 },   -- Bass Flute: was -7.52, +13.04
  { name = "Bass Clarinet XS", faderDb = -1.16, extraDb = 0.00 },   -- Bass Clarinet: was -13.16, +12.00
  { name = "Viola XS", faderDb = 6.77, extraDb = 0.00 },   -- Viola: was -5.23, +12.00
  { name = "Crotales RM", faderDb = -7.18, extraDb = 0.00 },   -- Crotales: was 0.00, -7.18
  { name = "Glockenspiel RM", faderDb = -7.21, extraDb = 0.00 },   -- Glockenspiel: was 0.00, -7.21
  { name = "Xylophone RM", faderDb = -5.65, extraDb = 0.00 },   -- Xylophone: was 0.00, -5.65
  { name = "Marimba RM", faderDb = 9.27, extraDb = 0.00 },   -- Marimba: was 0.00, +9.27
  { name = "Bongos ARO", faderDb = 4.35, extraDb = 0.00 },   -- Bongos: was 0.00, +4.35
  { name = "Shime Daiko ARO", faderDb = 4.92, extraDb = 0.00 },   -- Shime Daiko: was 0.00, +4.92
  { name = "China Cymbal ARO", faderDb = -3.99, extraDb = 0.00 },   -- China Cymbals: was 0.00, -3.99
  { name = "Spring Coil ARO", faderDb = 6.87, extraDb = 0.00 },   -- Spring Coil: was 0.00, +6.87
  { name = "Suspended Cymbals ARO", faderDb = 7.53, extraDb = 0.00 },   -- Suspended Cymbals Bright: was 0.00, +7.53
  { name = "Toms ARO", faderDb = -2.99, extraDb = 0.00 },   -- Toms High: was 0.00, -2.99
  { name = "Cello XS", faderDb = 8.13, extraDb = 0.00 },   -- Cello: was -3.87, +12.00
  { name = "Wood Blocks ARO", faderDb = 7.05, extraDb = 0.00 },   -- Wood Blocks: was 7.05, +0.00
  { name = "Bass Drum Alt ARO", faderDb = -4.29, extraDb = 0.00 },   -- Bass Drum (Alt): was -4.29, +0.00
}
local function findTrack(name)
  for i = 0, reaper.CountTracks(0) - 1 do
    local tr = reaper.GetTrack(0, i); local _, n = reaper.GetTrackName(tr)
    if n == name then return tr end
  end
end
local function findFx(tr)
  for i = 0, reaper.TrackFX_GetCount(tr) - 1 do
    local _, nm = reaper.TrackFX_GetFXName(tr, i, '')
    if nm:lower():find('volume adjustment', 1, true) or nm:lower():find('utility/volume', 1, true) then return i end
  end
end
local done, missing = {}, {}
for _, r in ipairs(TRIMS) do
  local tr = findTrack(r.name)
  if not tr then missing[#missing + 1] = r.name
  else
    reaper.SetMediaTrackInfo_Value(tr, 'D_VOL', 10 ^ (r.faderDb / 20))
    local fx = findFx(tr)
    local fxDb, fxParam = nil, nil
    if r.extraDb ~= 0 or fx then
      if not fx then fx = reaper.TrackFX_AddByName(tr, JS_NAME, false, -1) end
      if fx and fx >= 0 then
        reaper.TrackFX_SetEnabled(tr, fx, true)
        reaper.TrackFX_SetParam(tr, fx, 0, r.extraDb)
        local _, pn = reaper.TrackFX_GetParamName(tr, fx, 0, '')
        fxDb, fxParam = reaper.TrackFX_GetParam(tr, fx, 0), pn
      else fx = nil end
    end
    local volDb = 20 * math.log(reaper.GetMediaTrackInfo_Value(tr, 'D_VOL'), 10)
    done[#done + 1] = { name = r.name, faderAsked = r.faderDb, faderDb = math.floor(volDb * 100 + 0.5) / 100,
                        extraAsked = r.extraDb, fxIndex = fx, fxDb = fxDb and math.floor(fxDb * 100 + 0.5) / 100 or nil, fxParam = fxParam,
                        ok = math.abs(volDb - r.faderDb) < 0.05 and (r.extraDb == 0 or (fxDb ~= nil and math.abs(fxDb - r.extraDb) < 0.05)) }
  end
end
local allOk = #missing == 0
for _, d in ipairs(done) do if not d.ok then allOk = false end end
return { ok = allOk, applied = #done, missingTracks = missing, tracks = done, note = 'not saved — his CTRL+S' }
