-- load_rm_crotales.lua — the Ricotti CROTALES, loaded and laid out by script (the new-piece protocol's 4.3 · 4.4;
-- RUNNING_LOG §20). GENERATED by tools/ricotti_loaders.js from bank/ricotti_catalog.json — edit the catalog, not this file.
-- Run inside the Kontakt of the track "Crotales RM" (port DECCrotales): KONTAKT menu -> Run Lua script... -> this file,
-- or drag this file onto that Kontakt.
-- 9 slots, one per patch, each on its own MIDI channel [A] 1 .. 9. Idempotent: a slot of the same name is
-- re-configured, never loaded twice. Nothing is removed.
-- SELF-REPORTING: writes reaper/kontakt/out/load_rm_crotales_START_<time>.json before it touches Kontakt, then
-- ALWAYS load_rm_crotales_<time>.json with the read-back, or the error. The AI reads that file.

local OUT_DIR = 'C:/Users/jwloy/GitHub/decibel_TENOR_2026/reaper/kontakt/out/'
local ROOT = 'C:/Users/jwloy/Spitfire/Spitfire Ricotti Mallets library/Instruments'
local TAG = 'load_rm_crotales'
local PATCHES = {
  { ch = 1, name = 'Crotales - Main (Felt)', nki = ROOT .. '/_Individual patches_/c - Crotales - Main (Felt).nki' },
  { ch = 2, name = 'Crotales - Main (Metal damped)', nki = ROOT .. '/_Individual patches_/c - Crotales - Main (Metal damped).nki' },
  { ch = 3, name = 'Crotales - Main (Metal)', nki = ROOT .. '/_Individual patches_/c - Crotales - Main (Metal).nki' },
  { ch = 4, name = 'Crotales - Main (Plastic damped)', nki = ROOT .. '/_Individual patches_/c - Crotales - Main (Plastic damped).nki' },
  { ch = 5, name = 'Crotales - Main (Plastic)', nki = ROOT .. '/_Individual patches_/c - Crotales - Main (Plastic).nki' },
  { ch = 6, name = 'Crotales - Bowed', nki = ROOT .. '/_Individual patches_/c - Crotales - Bowed.nki' },
  { ch = 7, name = 'Crotales - Rolls (Metal)', nki = ROOT .. '/_Individual patches_/c - Crotales - Rolls (Metal).nki' },
  { ch = 8, name = 'Crotales - Rolls (Plastic)', nki = ROOT .. '/_Individual patches_/c - Crotales - Rolls (Plastic).nki' },
  { ch = 9, name = 'Crotales - Rolls (Rubber)', nki = ROOT .. '/_Individual patches_/c - Crotales - Rolls (Rubber).nki' },
}

local log, made = {}, {}
local BS = string.char(92)   -- no backslash in this source
local function q(s) return '"' .. tostring(s):gsub('[%c"' .. BS .. ']', ' ') .. '"' end
local function note(k, v) log[#log + 1] = ' ' .. q(k) .. ': ' .. (type(v) == 'string' and q(v) or tostring(v)) end
local function write_out(name, body) local f = assert(io.open(OUT_DIR .. name, 'wb')); f:write(body); f:close() end
local stamp = os.date('%Y%m%d_%H%M%S')

write_out(TAG .. '_START_' .. stamp .. '.json', '{ "kontakt_api": ' .. tostring(Kontakt ~= nil) .. ', "lua": ' .. q(_VERSION) .. ' }\n')

local function free_index()
  if Kontakt.get_free_instrument_index then return Kontakt.get_free_instrument_index() end
  return #Kontakt.get_instrument_indices() * 128
end

local function main()
  assert(Kontakt, 'no Kontakt API - developer features off, or not run inside Kontakt')
  note('instruments_before', #Kontakt.get_instrument_indices())
  for _, p in ipairs(PATCHES) do
    local idx, loaded = nil, false
    for _, i in ipairs(Kontakt.get_instrument_indices()) do if Kontakt.get_instrument_name(i) == p.name then idx = i end end
    if not idx then
      local ok, r = pcall(Kontakt.load_instrument, p.nki, free_index())
      assert(ok and type(r) == 'number', 'load failed for ' .. p.name .. ': ' .. tostring(r))
      idx, loaded = r, true
      local original = Kontakt.get_instrument_name(idx)
      pcall(Kontakt.set_instrument_name, idx, p.name)
      note('original_name_ch' .. p.ch, original)
    end
    pcall(Kontakt.set_instrument_midi_channel, idx, p.ch)
    made[#made + 1] = string.format('  {"name":%s,"idx":%d,"loaded_now":%s,"midi_channel":%s,"output_channel":%s,"volume_dB":%s}',
      q(Kontakt.get_instrument_name(idx)), idx, tostring(loaded), tostring(Kontakt.get_instrument_midi_channel(idx)), tostring(Kontakt.get_instrument_output_channel(idx)), tostring(Kontakt.get_instrument_volume(idx)))
  end
  note('instruments_after', #Kontakt.get_instrument_indices())
end

local ok, err = pcall(main)
note('ok', ok); if not ok then note('error', err) end
note('time', os.date('!%Y-%m-%dT%H:%M:%SZ'))
local text = '{\n' .. table.concat(log, ',\n') .. ',\n "slots": [\n' .. table.concat(made, ',\n') .. '\n ]\n}\n'
write_out(TAG .. '_' .. stamp .. '.json', text)
print('[' .. TAG .. '] ' .. text)
if not ok then error(err) end
