#!/usr/bin/env node
// apply_ricotti.js — THE PITCHED PERCUSSION LANE's techniques, GENERATED from bank/ricotti_catalog.json (the new-piece
// protocol's 4.5; RUNNING_LOG §34, 2026-10-04). The catalog → generator pattern of tools/apply_perc.js, for the
// Spitfire Ricotti Mallets: four instruments on ONE lane (his word, COMPOSITION_NOTES DEC-5), one Kontakt per
// instrument on its own port, one slot per patch on its own MIDI channel.
//
//   node tools/apply_ricotti.js [--dry]
//
// One technique per patch: its PORT is the instrument's (a technique's own port overrides the lane's — sonify_core),
// its CHANNEL the patch's, its range the catalog's (the patch's own, else the instrument's). A patch is PITCHED and
// loud by VELOCITY (a struck note: the velocity IS the dynamic — docs/DYNAMICS_LAW.md); a patch the catalog marks
// `byKey` (the two Glisses) is a KEY voice, its keys pending at his word. Written into sandbox/instruments.js as the
// generated block RICOTTI, applied at load by applyRicotti() onto the lane whose recipe key is LANE.
// Re-run after every change to the catalog; then node tools/palette_check.js · node tools/roster_check.js.
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..');
const CATALOG = path.join(ROOT, 'bank', 'ricotti_catalog.json'), RECIPE = path.join(ROOT, 'sandbox', 'instruments.js');
const LANE = 'bowed_vibraphone';   // the pitched percussion lane's INTERNAL key — piece #6's, kept (docs/NAMING.md § 1; NITS)
const PREFIX = { crotales: 'crot', glockenspiel: 'glock', xylophone: 'xylo', marimba: 'mar' };
const die = m => { console.error('apply_ricotti: ' + m); process.exit(1); };
const slugify = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
const CAT = JSON.parse(fs.readFileSync(CATALOG, 'utf8'));

const techs = [], insts = [], seen = new Set();
for (const I of CAT.instruments) {
  const pre = PREFIX[I.slug]; if (!pre) die(I.slug + ': no key prefix');
  if (!I.range) die(I.name + ': no range in the catalog yet');
  for (const p of I.patches) {
    const key = pre + '_' + slugify(p.label);
    if (seen.has(key)) die('two patches make the key ' + key); seen.add(key);
    const r = p.range || I.range;
    const q = { key, label: I.name + ' · ' + p.label, port: I.port, channel: p.channel, rangeLow: r.low, rangeHigh: r.high };
    if (p.byKey) { q.kind = 'key'; q.loud = 'vel'; q.keys = 'pending'; q.rangeLow = 36; q.rangeHigh = 107; }   // the glisses: blocks across the keyboard, unmapped at his word
    else { q.kind = 'pitched'; q.loud = 'vel'; }
    techs.push(q);
  }
  insts.push({ slug: I.slug, name: I.name, port: I.port, track: I.track, rangeLow: I.range.low, rangeHigh: I.range.high, patches: I.patches.length });
}

const BEGIN = '// ---- RICOTTI MALLETS (generated by tools/apply_ricotti.js from bank/ricotti_catalog.json — do not edit by hand) ----';
const END = '// ---- end of the Ricotti mallets ----';
const L = [];
L.push('const RICOTTI = {   // ' + insts.map(I => I.name + ' ' + I.patches + ' @' + I.port + ' ' + I.rangeLow + '–' + I.rangeHigh).join(' · ') + ' — generated ' + new Date().toISOString().slice(0, 10));
L.push('  lane: ' + JSON.stringify(LANE) + ',');
L.push('  instruments: [');
for (const I of insts) L.push('    ' + JSON.stringify(I).replace(/"([a-zA-Z]+)":/g, '$1: ').replace(/,/g, ', ') + ',');
L.push('  ],');
L.push('  techniques: [');
for (const q of techs) L.push('    { ' + Object.entries(q).map(([k, v]) => k + ': ' + JSON.stringify(v)).join(', ') + ' },');
L.push('  ],');
L.push('};');
L.push('function applyRicotti(all, gen) {   // the lane\'s roster IS the generated one; the lane entry above carries only what is the lane\'s (label, ordinary, channels)');
L.push('  const M = all[gen.lane]; if (!M) throw new Error("RICOTTI: no lane " + gen.lane);');
L.push('  M.techniques = gen.techniques.map(q => Object.assign({}, q));');
L.push('  M.malletInstruments = gen.instruments.map(I => Object.assign({}, I));');
L.push('  if (!M.techniques.some(q => q.key === M.ordinary)) throw new Error("RICOTTI: the lane\'s ordinary voice " + M.ordinary + " is not a patch of the catalog");');
L.push('}');
L.push('applyRicotti(INSTRUMENTS, RICOTTI);');
const block = BEGIN + '\n' + L.join('\n') + '\n' + END;

let s = fs.readFileSync(RECIPE, 'utf8');
const crlf = s.includes('\r\n'); if (crlf) s = s.split('\r\n').join('\n');
const i = s.indexOf(BEGIN), j = s.indexOf(END);
if (i >= 0 && j > i) s = s.slice(0, i) + block + s.slice(j + END.length);
else {
  const anchor = '// ---- end of the ARO percussion ----';
  const k = s.indexOf(anchor); if (k < 0) die('no anchor: ' + anchor);
  s = s.slice(0, k + anchor.length) + '\n\n' + block + s.slice(k + anchor.length);
}
console.log(insts.map(I => I.name + ': ' + I.patches + ' patches, ' + I.port + ', ' + I.rangeLow + '–' + I.rangeHigh).join('\n'));
console.log(techs.length + ' techniques' + (process.argv.includes('--dry') ? ' (dry run, nothing written)' : ''));
if (!process.argv.includes('--dry')) fs.writeFileSync(RECIPE, crlf ? s.split('\n').join('\r\n') : s);
