#!/usr/bin/env node
// build_first_sound.js — THE FIRST SOUND: one note on every TRACK of the rack, in a save the composer score opens
// (the new-piece protocol's 4.6; RUNNING_LOG §35, 2026-10-04). His ask: "can you put a note on each lane in a save file".
//
//   node tools/build_first_sound.js [--out scores/decibel-first-sound.json]
//
// Sixteen notes, one after another, in lane order — so each is heard alone and a silent one is plain:
//   the bass flute and the bass clarinet (their ordinary voices) · the EIGHT percussion instruments, one hit each (the
//   first key of each one's first beater) · the FOUR mallet instruments, one note each (a main patch) · the viola · the cello.
// Plain notes, at mf: a flat curve, no bend, no fade — the only question is "does this track sound from the app".
// Each note carries its name in its performance note, so the score says what should be sounding.
// The note object is the composer's own `waveCurve`, written as tools/build_1b5_score.js wrote piece #6's
// verification score. GENERATED — do not hand-edit; re-run after a change to the recipes.
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const OUT = path.join(ROOT, arg('out', 'scores/decibel-first-sound.json'));
if (/[\\/]piece-/.test(OUT)) { console.error('refusing a piece-… name'); process.exit(3); }

const INSTRUMENTS = vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'sandbox', 'instruments.js'), 'utf8') + '\n;INSTRUMENTS;', {});
const html = fs.readFileSync(path.join(ROOT, 'score', 'public', 'composer.html'), 'utf8');
const TRACKS = vm.runInNewContext(html.match(/const TRACKS = (\[[\s\S]*?\]);/)[1], {});
const laneOf = {}; TRACKS.forEach((t, i) => { laneOf[t.instKey] = i; });
const MF = 5.714285714285714;   // the written height of mf (4/7 of the 0–10 scale)

const plan = [];
const add = (instKey, techKey, midi, dur, name) => {
  const I = INSTRUMENTS[instKey]; if (!I) throw new Error('no instrument ' + instKey);
  const q = I.techniques.find(t => t.key === techKey); if (!q) throw new Error(instKey + ': no technique ' + techKey);
  if (q.rangeLow != null && (midi < q.rangeLow || midi > q.rangeHigh)) throw new Error(name + ': key ' + midi + ' outside ' + q.rangeLow + '–' + q.rangeHigh);
  plan.push({ instKey, techKey, midi, dur, name: name + ' — ' + q.label });
};
add('bass_flute', INSTRUMENTS.bass_flute.ordinary, 60, 2, 'Bass flute');
add('bass_clarinet', INSTRUMENTS.bass_clarinet.ordinary, 50, 2, 'Bass clarinet');
for (const A of INSTRUMENTS.percussion.aroInstruments || []) {   // every Abbey Road instrument of the selection: its first beater, its first key
  const q = INSTRUMENTS.percussion.techniques.find(t => t.channel === A.channel && Array.isArray(t.keys) && (t.key === A.slug || t.key.startsWith(A.slug + '_')));
  if (!q) throw new Error('percussion: no technique for ' + A.slug);
  add('percussion', q.key, q.keys[0].midi, 1.2, 'Percussion ch ' + A.channel);
}
for (const [techKey, midi] of [['crot_main_metal', 72], ['glock_main_hard', 72], ['xylo_main', 72], ['mar_main', 60]]) add('bowed_vibraphone', techKey, midi, 1.2, 'Mallets');
add('viola', INSTRUMENTS.viola.ordinary, 64, 2, 'Viola');
add('cello', INSTRUMENTS.cello.ordinary, 57, 2, 'Cello');

const objects = []; let nid = 1, t = 2;
for (const p of plan) {
  objects.push({
    id: 'wc-' + (nid++), type: 'waveCurve', layer: laneOf[p.instKey],
    startSeconds: Math.round(t * 1000) / 1000, endSeconds: Math.round((t + p.dur) * 1000) / 1000,
    nodes: [{ pos: 0, y: MF, smooth: 0.25 }, { pos: 1, y: MF, smooth: 0.25 }],
    segments: [{ model: 'bezier', slope: 0 }],
    color: '#4F7942', fillMode: 'bottom', opacity: 0.5,
    performanceNotes: p.name, properties: {}, sonifyNote: p.midi, technique: p.techKey,
  });
  p.at = t; t += p.dur + 1;
}
const now = new Date().toISOString();
const save = {
  version: 1, layoutVersion: 8, tracks: TRACKS, assets: {},
  metadata: { created: now, modified: now, note: 'THE FIRST SOUND (container 4, 4.6) — one note on every track of the rack, one after another, at mf. GENERATED by tools/build_first_sound.js; do not hand-edit.' },
  objects, markers: [], databases: {}, nextId: nid + 2, viewport: { pixelsPerSecond: 30, scrollOffset: 0 },
};
fs.writeFileSync(OUT, JSON.stringify(save, null, 1) + '\n');
console.log(path.relative(ROOT, OUT) + ' — ' + objects.length + ' notes, ' + Math.round(t) + ' s');
for (const p of plan) console.log('  ' + String(p.at).padStart(5) + ' s  ' + TRACKS[laneOf[p.instKey]].short.padEnd(5) + ' key ' + String(p.midi).padStart(3) + '  ' + p.name);
