#!/usr/bin/env node
// build_first_object.js — THE FIRST ELECTRONICS OBJECT, as a save the composer score opens (PLAN 1.1 · 6.6; RUNNING_LOG §64).
//
//   node tools/build_first_object.js [--out scores/decibel-first-object.json]
//
// Three things on the bass clarinet's lane, and nothing else:
//   5.0 s   a NOTE — D3 (key 50), two seconds, mf, the ordinary voice
//   4.9 s   a MIC OPENING over it — 500 ms, 100 ms before the note; its name bcl-A, its category attack
//   8.0 s   a RETURN of bcl-A — three seconds after the note
// Played with the engine up (start_electronics.bat): the note sounds, the engine records the window, crops it to the
// attack and banks it as bank/samples/bcl-A.wav; three seconds later the sample comes back through ELEC RETURN.
// The two bricks are zones with the engine's models (electronics/score/le_objects.js): elecOpen · elecPlay — written
// here with every field the composer's createZone gives a zone. The note is build_first_sound.js's.
// GENERATED — do not hand-edit; re-run after a change to the recipes or to the bricks' shape.
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const OUT = path.join(ROOT, arg('out', 'scores/decibel-first-object.json'));
if (/[\\/]piece-/.test(OUT)) { console.error('refusing a piece-… name'); process.exit(3); }

const INSTRUMENTS = vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'sandbox', 'instruments.js'), 'utf8') + '\n;INSTRUMENTS;', {});
const html = fs.readFileSync(path.join(ROOT, 'score', 'public', 'composer.html'), 'utf8');
const TRACKS = vm.runInNewContext(html.match(/const TRACKS = (\[[\s\S]*?\]);/)[1], {});
const ROUTE = JSON.parse(fs.readFileSync(path.join(ROOT, 'bank', 'elec_route.json'), 'utf8'));
const MF = 5.714285714285714;   // the written height of mf (4/7 of the 0–10 scale)

const player = ROUTE.players[0];   // the engine's first player — the bass clarinet
const lane = TRACKS.findIndex((t) => (INSTRUMENTS[t.instKey] || {}).port === player.port);
if (lane < 0) throw new Error('no lane plays on ' + player.port);
const I = INSTRUMENTS[TRACKS[lane].instKey], NOTE_AT = 5, NAME = player.name + '-A';

const zone = (id, model, start, end, color, yOffset, elec) => ({
  id, type: 'zone', layer: lane, startTime: start, endTime: end, player: '', instrument: '', zoneFunction: 'elec', midiModel: model,
  ostinatoParams: { smooth: 0.7, speed: 1.0, stretch: 1.5 }, chordMarkers: [], ratioMarkers: [], ratioSourceZoneId: '', ratioGroup: '',
  responseDelayMs: 0, jitterMs: 8, driftFactor: 0.02, midiSnippet: null, color, opacity: 0.35, yOffset, zoneHeight: 0.2,
  performanceNotes: '', properties: {}, elec,
});
const objects = [
  { id: 'wc-1', type: 'waveCurve', layer: lane, startSeconds: NOTE_AT, endSeconds: NOTE_AT + 2,
    nodes: [{ pos: 0, y: MF, smooth: 0.25 }, { pos: 1, y: MF, smooth: 0.25 }], segments: [{ model: 'bezier', slope: 0 }],
    color: '#4F7942', fillMode: 'bottom', opacity: 0.5, performanceNotes: 'Bass clarinet — the note the microphone opens on',
    properties: {}, sonifyNote: player.testNote, technique: I.ordinary },
  zone('zn-2', 'elecOpen', NOTE_AT - 0.1, NOTE_AT + 0.4, '#00897B', 0, { name: NAME, category: 'attack', player: player.name }),
  zone('zn-3', 'elecPlay', NOTE_AT + 3, NOTE_AT + 3.5, '#8E24AA', 1, { name: NAME }),
];
const now = new Date().toISOString();
const save = {
  version: 1, layoutVersion: 8, tracks: TRACKS, assets: {},
  metadata: { created: now, modified: now, note: 'THE FIRST ELECTRONICS OBJECT (PLAN 1.1 · 6.6) — a bass clarinet note, a mic opening over it, its sample returned three seconds later. Play it with the engine up. GENERATED by tools/build_first_object.js; do not hand-edit.' },
  objects, markers: [], databases: {}, nextId: 6, viewport: { pixelsPerSecond: 100, scrollOffset: 400 },
};
fs.writeFileSync(OUT, JSON.stringify(save, null, 1) + '\n');
console.log(path.relative(ROOT, OUT) + ' — on ' + TRACKS[lane].label + ' (lane ' + lane + '):');
console.log('  ' + (NOTE_AT - 0.1).toFixed(1) + ' s  mic opening ' + NAME + ', 500 ms');
console.log('  ' + NOTE_AT.toFixed(1) + ' s  the note, key ' + player.testNote + ', 2 s');
console.log('  ' + (NOTE_AT + 3).toFixed(1) + ' s  the return of ' + NAME);
